volumes:
  mongo_data:

services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    working_dir: /app/app/backend
    volumes:
      - ./app:/app/app
      - /app/node_modules
    command: sh -c "node server.js"
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/store
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy